### ISSUE TITLE
Finalização do CRUD e da autenticação 

### ISSUE THREAD

**Issue by EsdrasPedro** [EsdrasPedro/CL_Board.IPI.2P#10]
Essa epic precisa ser quebrada em outras histórias do usuário, spike e histórias técnicas.

- [x]  Encerramento do CRUD 
- [x]  Encerrar sessão
- [x]  Guardar o nome de usuário
- [x] Função Listagem: Curso e Disciplina
